AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://snijhara/444f299ce92601de0eb071677093fba0
      Environment:
        Variables:
          S3_BUCKET: snijhara
      Handler: index.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
