AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Question written with SpringBoot with the aws-serverless-java-container library

Resources:
  QuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.postgresdemo.StreamLambdaHandler::handleRequest
      Runtime: java8 
      CodeUri: target/postgres-demo-serverless-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60  
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET

Outputs:

    QuestionApi:
      Description: "API Gateway endpoint URL for Prod stage for Question function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/questions/"

    QuestionFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt QuestionFunction.Arn

    QuestionIamRole:
      Description: "Implicit IAM Role created for Quest function"
      Value: !GetAtt QuestionFunctionRole.Arn
