#This is a working sample
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tag Engine API gateway and lambda deployment

Resources:
  QuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.postgresdemo.StreamLambdaHandler::handleRequest
      FunctionName: poc-function
      Runtime: java8 
      CodeUri: target/-postgres-demo-serverless-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: 
              Ref: QuestionApi
            
 
  QuestionApi:
     Type: AWS::Serverless::Api
     Properties:
       StageName: dev
       DefinitionUri: Question-dev-swagger-apigateway.json
       
Outputs:

 QuestionApi:
    Description: "API Gateway endpoint URL for dev stage "
    Value: !Sub "https://${QuestionApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"

 QuestionFunction:
   Description: "Lambda Function ARN"
   Value: !GetAtt QuestionFunction.Arn
                     


 