AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tag Engine API gateway and lambda deployment

Resources:
  TagEngineFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.savkar.tagEngine.TagLambdaHandler::handleRequest
      FunctionName: tag-engine-function
      Runtime: java8 
      CodeUri: target/tagEngine-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: 
              Ref: TagEngineAPI
            
 
  TagEngineAPI:
     Type: AWS::Serverless::Api
     Properties:
       StageName: dev
       DefinitionUri: TagEngine-dev-swagger-apigateway.json
       
Outputs:

 TagEngineAPI:
    Description: "TagEngine API Gateway endpoint URL for dev stage for TagEngineFunction"
    Value: !Sub "https://${TagEngineAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/"

 TagEngineFunction:
   Description: "TagEngine Lambda Function ARN"
   Value: !GetAtt TagEngineFunction.Arn
                     


 